# Datenbereinigung Eniac
Dies ist das komplette, geordnete Bereinigungsskript (kurz und knapp).

## 1. Libraries einlesen

In [3]:
import pandas as pd
import numpy as np

## 2. Datensätze einlesen und Kopien erstellen

In [4]:
df_brands_org = pd.read_csv("Daten/brands.csv")
df_olines_org = pd.read_csv("Daten/orderlines.csv")
df_orders_org = pd.read_csv("Daten/orders.csv")
df_products_org = pd.read_csv("Daten/products.csv")

df_brands = df_brands_org.copy()
df_olines = df_olines_org.copy()
df_orders = df_orders_org.copy()
df_products = df_products_org.copy()

### 2.1 Datentypen herausfinden

Einfache Methode:

In [5]:
display(df_brands.info())
display(df_olines.info())
display(df_orders.info())
display(df_products.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   short   187 non-null    object
 1   long    187 non-null    object
dtypes: object(2)
memory usage: 3.1+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 293983 entries, 0 to 293982
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                293983 non-null  int64
 1   id_order          293983 non-null  int64
 2   product_id        293983 non-null  int64
 3   product_quantity  293983 non-null  int64
 4   sku               293983 non-null  object
 5   unit_price        293983 non-null  object
 6   date              293983 non-null  object
dtypes: int64(4), object(3)
memory usage: 15.7+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226909 entries, 0 to 226908
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   order_id      226909 non-null  int64
 1   created_date  226909 non-null  object
 2   total_paid    226904 non-null  float64
 3   state         226909 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 6.9+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  object
 4   promo_price  19326 non-null  object
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.0+ MB

None

### Darsellung in Tabelle
+ fehlende Werte werden mit X ersetzt
+ Ausgabe in CSV und Txt Format

In [6]:
dt_vergleich = pd.concat([
    df_brands.dtypes.rename('Brands'),
    df_olines.dtypes.rename('Order Lines'),
    df_orders.dtypes.rename('Orders'),
    df_products.dtypes.rename('Products')
], axis=1)

display(dt_vergleich.fillna(' '))

# Die Tabelle mit 'X' füllen und als CSV exportieren
dt_vergleich.fillna('X').to_csv('datentypen_uebersicht.csv', index=True, sep=';', encoding='utf-8')
# Die Tabelle als formatierten Text in eine .txt-Datei schreiben
with open('datentypen_uebersicht.txt', 'w', encoding='utf-8') as f:
    f.write(dt_vergleich.fillna(' ').to_string())

                  Brands Order Lines   Orders Products
short             object
long              object
id                             int64
id_order                       int64
product_id                     int64
product_quantity               int64
sku                           object            object
unit_price                    object
date                          object
order_id                                int64
created_date                           object
total_paid                            float64
state                                  object
name                                            object
desc                                            object
price                                           object
promo_price                                     object
in_stock                                         int64
type                                            object

### 2.2 Datentype anpassen
Anpassen der Zeile für den passenden Dtype

**2.2.1 Datumsspalten konvertieren**

In [7]:
df_olines['date'] = pd.to_datetime(df_olines['date'], errors='coerce')
df_orders['created_date'] = pd.to_datetime(df_orders['created_date'], errors='coerce')

**2.2.2 Preise in Fließkommazahlen umwandeln**

In [8]:

df_olines['unit_price'] = pd.to_numeric(df_olines['unit_price'], errors='coerce')
df_products['price'] = pd.to_numeric(df_products['price'], errors='coerce')
df_products['promo_price'] = pd.to_numeric(df_products['promo_price'], errors='coerce')

**2.2.3 Kontroll-Check** 

Wenn du deine Übersicht jetzt neu erstellst, 
sollten diese Spalten nun korrekt angezeigt werden!

## 3. Duplikate finden und entfernen
Header anzeigen mit einer Zeile

In [9]:
## header anzeigen
display(df_brands.tail(1))
print("---------------------------------------------------------------------------------------")
display(df_olines.tail(1))
print("---------------------------------------------------------------------------------------")
display(df_orders.tail(1))
print("---------------------------------------------------------------------------------------")
display(df_products.tail(1))
print("---------------------------------------------------------------------------------------")

    short  long
186   ZEP  Zepp

---------------------------------------------------------------------------------------

,id,id_order,product_id,product_quantity,sku,unit_price,date
293982,1650203,527401,0,1,APP0927,13.99,2018-03-14 13:58:36

---------------------------------------------------------------------------------------

        order_id        created_date  total_paid        state
226908    527401 2018-03-14 13:58:36       18.98  Place Order

---------------------------------------------------------------------------------------

,sku,name,desc,price,promo_price,in_stock,type
19325,THU0063,"Enroute Thule 14L Backpack MacBook 13 ""Green",Backpack with capacity of 14 liter compartment...,69.95,649.903,1,1392

---------------------------------------------------------------------------------------


### ALTERNATIVER CODE

```
anzahl_duplikate = df_brands.duplicated().sum()
anzahl_duplikate = df_olines.duplicated().sum()
anzahl_duplikate = df_orders.duplicated().sum()
```
**#Checkt, ob nur die Order-ID mehrfach vorkommt**
```
anzahl_duplikate = df_olines.duplicated(subset=['id_order']).sum()
print(f"Doppelte Order-IDs: {anzahl_duplikate}")

```

Anzahl der Duplikate ermitteln

In [10]:
anzahl_duplikate = df_products.duplicated().sum()
print(f"Gefundene Duplikate vor der Bereinigung: {anzahl_duplikate}")

if anzahl_duplikate > 0:
    print("\nBetroffene Zeilen und deren Inhalt:")
    # Hier nutzen wir jetzt display() statt print()
    display(df_products[df_products.duplicated(keep='first')])

Gefundene Duplikate vor der Bereinigung: 8746

Betroffene Zeilen und deren Inhalt:

,sku,name,desc,price,promo_price,in_stock,type
101,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199.00,NaN,0,1282
102,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199.00,NaN,0,1282
103,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199.00,NaN,0,1282
104,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199.00,NaN,0,1282
105,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199.00,NaN,0,1282
...,...,...,...,...,...,...,...
16831,APP2302,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,NaN,NaN,0,"1,02E+12"
16833,APP2303,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13 inch Touch Bar 33 GHz Core ...,NaN,NaN,0,"1,02E+12"
18190,PAR0077,Parrot Bebop Drone 2 Power,Drone cuadricóptero quality camera integrated ...,699.90,NaN,0,11905404
18308,NKI0010,Nokia Wireless sphygmomanometer Plata,Sphygmomanometer for iPhone iPad and iPod App.,129.99,NaN,1,11905404
18514,PLA0035,Bluetooth Headset Plantronics Explorer 80,egonómico wireless headset design for iPhone i...,39.99,349.896,1,5384



Gefundene exakte Duplikate bei Products: 8.746

In [11]:
# Löscht Duplikate und behält das jeweils erste Vorkommen
df_products = df_products.drop_duplicates()

print(f"Neue Shape nach Duplikat-Entfernung: {df_products.shape}")

Neue Shape nach Duplikat-Entfernung: (10580, 7)

In [12]:
# Zeigt an, wie viele Werte durch 'coerce' zu NaN wurden
#print(df_products_clean['price'].isna().sum())
#mini_products = pd.read_csv("Daten/products.csv", nrows=5)
#display(mini_products)
df_products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10580 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10580 non-null  object
 1   name         10580 non-null  object
 2   desc         10573 non-null  object
 3   price        10157 non-null  float64
 4   promo_price  5983 non-null   float64
 5   in_stock     10580 non-null  int64
 6   type         10530 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 661.2+ KB

## 5. Logikfehler beheben
Promo-Preis darf nicht größer sein als der reguläre Preis.

In [13]:
# Zuerst Zeilen löschen, die bei der Typ-Umwandlung kaputtgegangen sind (unsaubere Werte)
df_products = df_products.dropna(subset=['price', 'promo_price'])

# Filter anwenden: Wir behalten nur Zeilen, bei denen Promo-Preis <= Normalpreis ist
df_products = df_products[df_products['promo_price'] <= df_products['price']]

## 6. Fehlende Werte behandeln
Letzte verbleibende NaNs aus Orders (total_paid) und Products (desc, type) löschen.

In [14]:
# Orderlines: Alle Zeilen löschen, bei denen der unit_price fehlt (NaN ist)
df_olines = df_olines.dropna(subset=['unit_price'])

# Products: Alle Zeilen löschen, bei denen price oder promo_price fehlt (NaN ist)
df_products = df_products.dropna(subset=['price', 'promo_price'])
df_products.drop(columns=['promo_price'], inplace=True)

# Products: Fehlende Werte in den Text-Spalten 'desc' und 'type' löschen
df_products = df_products.dropna(subset=['desc', 'type'])

## 7. Qualitätskontrolle (Check)
Prüfen, ob alle Tabellen sauber sind (0 Duplikate, 0 fehlende Werte).

In [15]:
dataframes = {
    "Brands": df_brands,
    "Orderlines": df_olines,
    "Orders": df_orders,
    "Products": df_products
}

for name, df in dataframes.items():
    print(f"=== {name} ===")
    print(f"Zeilen / Spalten: {df.shape}")
    print(f"Duplikate: {df.duplicated().sum()}")
    fehlende = df.isna().sum().sum()
    print(f"Fehlende Werte (gesamt): {fehlende}")
    print("-" * 40)

=== Brands ===
Zeilen / Spalten: (187, 2)
Duplikate: 0
Fehlende Werte (gesamt): 0
----------------------------------------
=== Orderlines ===
Zeilen / Spalten: (257814, 7)
Duplikate: 0
Fehlende Werte (gesamt): 0
----------------------------------------
=== Orders ===
Zeilen / Spalten: (226909, 4)
Duplikate: 0
Fehlende Werte (gesamt): 5
----------------------------------------
=== Products ===
Zeilen / Spalten: (1252, 6)
Duplikate: 0
Fehlende Werte (gesamt): 0
----------------------------------------

## 8. Export
Saubere Datensätze abspeichern.

In [16]:
df_brands.to_csv("Daten/clean/brands_clean.csv", index=False)
df_olines.to_csv("Daten/clean/orderlines_clean.csv", index=False)
df_orders.to_csv("Daten/clean/orders_clean.csv", index=False)
df_products.to_csv("Daten/clean/products_clean.csv", index=False)
print("Export-Code ist auskommentiert, zur Nutzung Rauten entfernen.")

Export-Code ist auskommentiert, zur Nutzung Rauten entfernen.

## Auswertung & Kritik

Dieses Skript ist genau der Übeltäter, der für den massiven Umsatzverlust (von 15,7 Mio. € auf ca. 7-8 Mio. €) verantwortlich ist!

Warum? Beim Schritt 2.2.2 Preise in Fließkommazahlen umwandeln nutzt das Skript den Befehl pd.to_numeric(..., errors='coerce'). Das bedeutet: Alles, was kein perfekter Punkt ist (wie die Preise 1.137.99 mit zwei Punkten), wird sofort in NaN (Not a Number) verwandelt. Beim Schritt 6. Fehlende Werte behandeln löscht das Skript dann eiskalt alles, was ein NaN enthält.

Dadurch passiert Folgendes (wie man in Zelle 13 sieht):

Die products-Tabelle schrumpft auf mickrige 1.252 Produkte zusammen (vorher waren es über 10.000 einzigartige Produkte)! Fast 90% des Sortiments wurden gelöscht.
Eure saubere products_clean.csv hat also fast keine Produkte mehr, was den anschließenden Merge mit den Bestellungen ruiniert.